### ISSUE TITLE
Can't automagically start on Ubuntu

### ISSUE THREAD

**Issue by fwsGonzo** [Fitblip/wsstat#3]
At first:
```
$ pip install wsstat
Collecting wsstat
  Using cached wsstat-1.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3vqNNt/wsstat/setup.py", line 11, in <module>
        raise Exception("websockets requires Python >= 3.3.")
    Exception: websockets requires Python >= 3.3.
```
However, installing wsstat using pip3 (pip for python3):
```
Successfully built urwid
Installing collected packages: websockets, urwid, asyncio, appdirs, six, pyparsing, packaging, setuptools, py, pytest, wsstat
Successfully installed appdirs asyncio packaging py pyparsing pytest setuptools-20.7.0 six-1.10.0 urwid websockets-3.0 wsstat
```
works.. except I can't just run wsstat:
```
$ wsstat
wsstat: command not found
$ python3 wsstat
python3: can't open file 'wsstat': [Errno 2] No such file or directory
```

**Comment by Fitblip** [comment]
Hey @fwsGonzo, thanks for the bug report!

I'd suggest removing both copies and trying again, since with pip it's a race between python 2 and 3 as to who gets the executable in `$PATH`. A good example is `ipython`, if you `pip3 install ipython` then `pip install ipython`, the `ipython` executable will always be the python3 version, but if you do it in the opposite order, the installer will actually make 2 separate executables - `ipython` + `ipython3`.

Here's the steps I'd recommend following:
`pip uninstall wsstat`
`pip3 uninstall wsstat`
`pip install wsstat`
`wsstat --demo`

Please let me know if this doesn't help and we can debug together!

**Comment by fwsGonzo** [comment]
I see! Well, I got it to work at my home computer by only using pip3 so it's exactly as you say. Working as expected :) :+1:

**Comment by Fitblip** [comment]
Wonderful! I'm glad it worked out :) 

Also if you have any suggestions about things you'd like to see please let me know!
